=== Carlosrt15/practicas-y-proyectos/Lenguajes-Marcas/XML_DTD/ejercicio1.dtd
<!ELEMENT mensajeria (destinatario,producto+,diaEntrega)+>
<!ELEMENT destinatario (nombre,direccion)>
<!ATTLIST destinatario codCliente  ID #IMPLIED>
<!ELEMENT producto (tipo, importe)>
<!ELEMENT diaEntrega (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT importe (#PCDATA)>

=== Carlosrt15/practicas-y-proyectos/Lenguajes-Marcas/XML_DTD/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensajeria SYSTEM "ejercicio1.dtd">
<mensajeria>
    <destinatario codCliente= "c001">
        <nombre>Juan PÃ©rez</nombre>
        <direccion>Calle Falsa 123</direccion>
    </destinatario>
    <producto>
        <tipo>Libro</tipo>
        <importe>25.00</importe>
    </producto>
    <diaEntrega>2025-06-10</diaEntrega>
</mensajeria>
