=== Carlosrt15/practicas-y-proyectos/Lenguajes-Marcas/XML_DTD/ejercicio2.dtd
<!ELEMENT correos (remitente,destinatario+,asunto,contenido)>
<!ELEMENT remitente (nombre,direccion)>
<!ELEMENT destinatario (nombre,direccion)>
<!ATTLIST destinatario destPrincipal (si|no) #REQUIRED >
<!ELEMENT asunto EMPTY>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

=== Carlosrt15/practicas-y-proyectos/Lenguajes-Marcas/XML_DTD/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE correos SYSTEM "ejercicio2.dtd">

<correos>
    <remitente>
        <nombre>Juan</nombre>
        <direccion>Calle falsa</direccion>
    </remitente>

    <destinatario destPrincipal="si">
        <nombre>Maria</nombre>
        <direccion>Avenida real</direccion>
    </destinatario>

    <asunto/>
    <contenido>Nos reunimos a las 8</contenido>
</correos>
